module.exports = {
  '': require('./parantheses'),
  changeset: require('./meta'),
  count_distinct_members: require('./count_members'),
  count_members: require('./count_members'),
  count_by_role: require('./count_members'),
  count_distinct_by_role: require('./count_members'),
  debug: require('./debug'),
  id: require('./meta'),
  is_closed: require('./is_closed'),
  is_tag: require('./is_tag'),
  length: require('./length'),
  tag: require('./tag'),
  timestamp: require('./meta'),
  type: require('./meta'),
  count_tags: require('./count_tags'),
  uid: require('./meta'),
  user: require('./meta'),
  version: require('./meta')
}
